### ISSUE TITLE
Windows 11 builds from 22000.100 and above are being generated as 22000.1

### ISSUE THREAD

**Issue by sr229** [uup-dump/website#108]
Most likely a bug but generating ISOs from Windows 11 builds starting from 22000.100 to 22000.132 is broken as the version is matched as 22000.1

**Comment by abbodi1406** [comment]
Describe broken?
are you using Windows or Linux converter?
if you are using Windows converter, did you review the conversion progress for errors?

**Comment by abbodi1406** [comment]
You did not answer the questions

using Multiplatform converter will always generate 22000.1

using Windows converter will integrate the updates to produce 22000.x image
but the process is not error-prone and could result into generating 22000.1 image
