### ISSUE TITLE
Windows 11 Build 22000.168 build cannot be downloaded and I get this error

### ISSUE THREAD

**Issue by KianmehrKM** [uup-dump/website#109]
Hi, I'm trying to download the "Upgrade to Windows 11 (22000.168) amd64" from UUPdump and I get this error on CMD:
I tried redownloading the script many times and couldn't do it, what is the issue?
```
Extracting UUP converter... 

Retrieving aria2 script...

08/28 11:46:15 [NOTICE] Downloading 1 item(s)
[#34985e 0B/0B CN:1 DL:0B]
08/28 11:46:16 [NOTICE] Download complete: F:/22000168/files/aria2_script.9481.txt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
34985e|OK  |      32B/s|F:/22000168/files/aria2_script.9481.txt

Status Legend:
(OK):download completed.

Unable to retrieve data from Windows Update servers. Reason: EMPTY_FILELIST
If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.

Press any key to continue . . .


```

**Comment by KianmehrKM** [comment]
Also I checked the pinned issue and I tried that and couldn't get it to work, anymore things to say?

**Comment by LDY681** [comment]
Same issue here. Toggled off auto updates, still didn't work ._.

**Comment by KianmehrKM** [comment]
> Same issue here. Toggled off auto updates, still didn't work ._.

I went to UUPdump Discord server, seems Microsoft picked up the update from its server because the taskbar was not working totally, you can try the other one, aka Cumulative Update one, I downloaded it and it works perfectly, here's the link:
https://uupdump.net/selectlang.php?id=baed606a-3e38-4113-992a-1a2ffb238007

**Comment by LDY681** [comment]
> > Same issue here. Toggled off auto updates, still didn't work ._.
> 
> I went to UUPdump Discord server, seems Microsoft picked up the update from its server because the taskbar was not working totally, you can try the other one, aka Cumulative Update one, I downloaded it and it works perfectly, here's the link:
> https://uupdump.net/selectlang.php?id=baed606a-3e38-4113-992a-1a2ffb238007
I will give it a try. Thanks!
