### ISSUE TITLE
[Question] Channel

### ISSUE THREAD

**Issue by ImportTaste** [uup-dump/website#110]
Forgive me for asking, but does the channel listed on the site affect what channel the installed version of Windows will use when trying to update itself?

For instance, if I download an uupdump ISO converter labeled Release Preview, will the resulting Windows OS be using Release Preview for further updates, or will it remain on that build and wait for the Retail channel to catch up?

I ask because my current Windows OS, which is on the Retail channel, is using 19043.1200. However, on the website, that's currently only available as a Release Preview: https://uupdump.net/download.php?id=69e7b911-208f-4636-9f44-25f1e8e2a44d&pack=en-us

Thank you for your time.

**Comment by abbodi1406** [comment]
No it does not
official non-preview builds are all Retail when you clean install it

only the prerelease preview builds require insider program

**Comment by ImportTaste** [comment]
> only the prerelease preview builds require insider program

And these aren't even available through UUPdump, correct?

**Comment by abbodi1406** [comment]
> 
> And these aren't even available through UUPdump, correct?

except Windows 11 22000, all builds from dev channel are previews
https://uupdump.net/known.php?q=regex:[2-9]\d{4}\.
