### ISSUE TITLE
Failed to retrieve aria2 script - Ubuntu 20.04

### ISSUE THREAD

**Issue by SohaibRaza** [uup-dump/website#111]
Trying download Following version, but getting error:
Windows 11 Insider Preview **22454.1000** (rs_prerelease) amd64

Error  👇

``` ./uup_download_linux.sh 
Retrieving aria2 script...
./uup_download_linux.sh: line 55: aria2c: command not found
Failed to retrieve aria2 script
```

I am using **Ubuntu 20.04**

**Comment by luzeadev** [comment]
hey, run `sudo apt-get install cabextract wimtools chntpw genisoimage` and try again
