### ISSUE TITLE
Download through Aria2

### ISSUE THREAD

**Issue by BearoKevo** [uup-dump/website#116]
Hi, 

I have installed Aria2 on my Windows, but when running the download .cmd, it keeps saying the aria2.exe not found in the directory. 

Is there ways to get around this?

**Comment by BearoKevo** [comment]
[](url)

**Comment by abbodi1406** [comment]
Installed how?
the downloaded zip file already contain aria2c.exe
make sure to extract the whole zip file to a folder with short path, then run uup_download_windows.cmd
