### ISSUE TITLE
aria2_download_windows.cmd overwrites ConvertConfig.ini

### ISSUE THREAD

**Issue by ImportTaste** [uup-dump/website#12]
If ConvertConfig.ini exists in the same directory as aria2_download_windows.cmd already, then it was probably put there manually. Thus, it shouldn't be overwritten. Right now, I resort to commenting out line 61 to work around this issue.

Here is the fix, change `copy /y files\ConvertConfig.ini . >NUL` to `waitfor /t 2 copy /-y files\ConvertConfig.ini . >NUL`

Changing /y to /-y forces a prompt rather than suppresses it. (This is the default, but this ensures the highly rare COPYCMD env variable doesn't screw things up.)

waitfor /t 2 is a 2 second timeout as it waits for the command. Essentially, this means that if a prompt to overwrite occurs, which the user can't even see due to `>NUL`, it will move on after the 2 seconds elapse.

**Comment by whatever127** [comment]
The copy operation has to be done this way, because every time the script is run, the converter is extracted overriding everything including ConvertConfig.ini. I'll think about a better way which will allow to have custom ConvertConfig.ini in root directory of the archive.

For now replace the ConvertConfig.ini in files directory with your own instead of modifying script.

**Comment by ImportTaste** [comment]
I think you're misunderstanding. This line of the script copies ConvertConfig.ini from the files subdirectory to the root directory. My modification stops it if there is already a user-supplied ConvertConfig.ini in the root directory. It works just fine.

**Comment by whatever127** [comment]
> My modification stops it if there is already a user-supplied ConvertConfig.ini in the root directory. If there is no ConvertConfig.ini in the root directory, it copies just like before. It works just fine.

Then you had to modify also the line before this which is `"%a7z%" -y x "%uupConv%" >NUL`. This overrides your current config with the config which is supplied in the converter redistributable archive, which I have to replace with my own config which I distribute in `files` directory by using `copy /y files\ConvertConfig.ini . >NUL`.

**Comment by ImportTaste** [comment]
... I might have forgotten that I turned off auto-refresh in VSCode and I was looking at the old ini the entire time.

**Comment by whatever127** [comment]
The problem should be fixed now. I have modified 7-Zip command to skip extracting default ConvertConfig.ini and the copy command is only issued when the file does not exist.

**Comment by ImportTaste** [comment]
Thank you!
