### ISSUE TITLE
[Feature Request] UUP UpdateOS Download mode

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [uup-dump/website#123]
Can we have a option to download UUP and install it directly as updates *(cmd file example for directly installing updates is in zip file)* from your website?
[updateOS_19044.1415_en-us_amd64_professional.zip](https://github.com/uup-dump/website/files/7777019/updateOS_19044.1415_en-us_amd64_professional.zip)

**Comment by abbodi1406** [comment]
You mean installing the updates themselves? it's not hard to do it manually or via W10UI.cmd as example

doing in-place upgrade from UUP files directly is possible, but not easy
