### ISSUE TITLE
Unable to access UUP dump website in China

### ISSUE THREAD

**Issue by realYulin** [uup-dump/website#126]
I want to download windows 11 22000.376, but get this error code: ERR_CONNECTION_TIMED_OUT
I think this website has been blocked by the firewall in China.
The screenshot is below (in Chinese).
![67C82191-D0FA-425D-BAD7-F50F412EE147](https://user-images.githubusercontent.com/64626058/147864111-63d5b41d-a911-4ebe-9e4d-973c9faa842b.jpeg)

**Comment by luzeadev** [comment]
Hi, please try https://proxied.uupdump.net.

**Comment by sashaqwert** [comment]
> Hi, please try https://proxied.uupdump.net.

Thanks! This helped me in Russia.

<details>
<summary>Screenshot</summary>

![изображение](https://user-images.githubusercontent.com/24974508/148429207-6f784397-57e1-4807-841a-cfa6e1f3edc7.png)

</details>
