### ISSUE TITLE
Rename "Enterprise for virtual desktops" to "Enterprise multi-session" for Windows 11

### ISSUE THREAD

**Issue by sashaqwert** [uup-dump/website#127]
I suggest renaming "Enterprise for virtual desktops" to "Enterprise multi-session" for Windows 11, since Microsoft uses this revision name in Windows 11.
The old revision name remains in Windows 10.

**Comment by abbodi1406** [comment]
Dual renamed

**Comment by sashaqwert** [comment]
Thanks! So it became more convenient.
