### ISSUE TITLE
[feature request] aria2c - update 0.35 to 0.36

### ISSUE THREAD

**Issue by eladkarako** [uup-dump/website#129]
`https://github.com/uup-dump/website/blob/master/autodl_files/aria2c.exe`

https://github.com/aria2/aria2/releases/tag/release-1.36.0  
(or https://github.com/q3aql/aria2-static-builds/issues/19#issuecomment-907376464 )

mostly because of https://github.com/aria2/aria2/pull/1644 and https://github.com/aria2/aria2/pull/1487

<sub>b.t.w. to the batch files, I later also add: <code>--min-tls-version=TLSv1.2 --disable-ipv6=true</code> for better compatibility, <code>--min-split-size=5M</code> for more splits, <code>--check-certificate=false</code> to avoid certificate exchange issues, and <code>--file-allocation=falloc</code> to improve writing to disk (it has a huge impact).</sub>

**Comment by luzeadev** [comment]
`--min-tls-version=TLSv1.2`: it's already the default so no need to explicitly set it
`--disable-ipv6`: no, we're al(ready)*2 
`--min-split-size=5M`: doesn't really make a difference with the default 20M
`--check-certificate=false`: no, all of the web servers are either not using SSL at all or have a valid SSL certificate
`--file-allocation=falloc`: doesn't work on Windows

**Comment by eladkarako** [comment]
thanks!

<details><summary>;]</summary>

`--min-split-size=5M: doesn't really make a difference with the default 20M` - true, there are just 7 UUPs in size 5-20m, and that's not really needed.  
`--min-tls-version=TLSv1.2: it's already the default so no need to explicitly set it` - that's true I'm just making sure the server TLS context <a href="https://github.com/aria2/aria2/blob/faa6955c8d7bb7b6541e0b7fbb84f7d213f761ab/src/OptionHandlerFactory.cc#L517">won't switch</a> to TLS1.3 in future versions, but if the downloads are from http it isn't needed anyway..  
`--file-allocation=falloc: doesn't work on Windows` - well.. it does (w7sp1+) and it's awesome. but that's fine.  
`--check-certificate=false: no, all of the web servers are either not using SSL at all or have a valid SSL certificate` - it is not for the server, it is to avoid exchanging the client-PEM `ca-certificate` (optional). which some clients has issues with. but if the target server is not https, that's fine.  
</details>

**Comment by luzeadev** [comment]
u
