### ISSUE TITLE
Wrong FAQ link

### ISSUE THREAD

**Issue by theoware** [uup-dump/website#132]
For example on this page [22000.522](https://uupdump.net/selectlang.php?id=e852c215-2666-4f07-a443-ad93fe142e19) it links to the [FAQ](https://uupdump.net/faq.php) but this page doesnt exist.
Please change the link to the right [FAQ](https://github.com/uup-dump/website/blob/master/FAQ.md). Thanks!

**Comment by abbodi1406** [comment]
That would require modifying all langs files
the upper `? FAQ` probably suffice

**Comment by theoware** [comment]
Probabbly yes
