### ISSUE TITLE
fetchupd.php Functions do not work

### ISSUE THREAD

**Issue by meluvalli** [uup-dump/website#136]
Per https://github.com/uup-dump/api you can filter using arch and ring, however this does not work anymore.  

Example:

https://uupdump.net/fetchupd.php?ring=retail 

always results in Error "An error has occurred while attempting to process your request"

**Comment by abbodi1406** [comment]
You must specify the build, otherwise the api will check against latest build available in the database (currently 22557.1)
https://uupdump.net/fetchupd.php?ring=retail&build=19044.1

**Comment by meluvalli** [comment]
So there is no way to just get the latest build automatically?  This use to
work a while ago.

**Comment by meluvalli** [comment]
It use to just pull all builds matching the criteria.

**Comment by abbodi1406** [comment]
> So there is no way to just get the latest build automatically? This use to work a while ago.

it only works for Dev, other channels require source build to check against
