### ISSUE TITLE
The Generated Iso is missing Vital System Apps

### ISSUE THREAD

**Issue by SunnyM00n** [uup-dump/website#140]
Generating a Dev-Insider Iso with Build 22567.1 from the Downloaded script causes the resulting Windows Installation to lack vital Apps like the Windows Store, the Security Center and a bunch of preinstalled Apps like Notepad, Movies&TV etc.

**Comment by JonatanCz** [comment]
I confirm, in Windows start menu there are only:
- "Accessibility" (folder),
- "File Explorer",
- "Get started",
- "Microsoft Edge",
- "Microsoft Teams",
- "Print Queue Action Center" (not opening),
- "Settings" (also not opening),
- "Windows Tools".

Can open notepad (eg. with Win+R) but it has the old non-metro UI.
Installed Windows version: 10.0.22567.1 (it was like that on older ones as well).

**Comment by abbodi1406** [comment]
22563+ will lack all "outbox" UWP Apps, because they are now delivered separately
adding them to install.wim will need some work

**Comment by JonatanCz** [comment]
Is there any temporary solution? Downloading all the needed .appx files and installing them manually?

**Comment by abbodi1406** [comment]
You can download the Apps files by choosing "Any Language" from language selection box

adding the Apps to install.wim is another not-easy task
i'm trying to create a script for that soon

P.S. you can install Store manually after installing OS by running the command `WSReset.exe -i`

**Comment by JonatanCz** [comment]
Thank you! `wsreset` worked for installing Microsoft Store. Now I'll try to download the apps.

**Comment by JonatanCz** [comment]
One more question. Do I need to install all language versions for files like `VoiceRecorderStub_1.0.42.0_language-**.appx` (where `**` is short language code) or only the ones I'm interested in?

**Comment by SunnyM00n** [comment]
I actually found a workaround. I gathered the App files and made a short script that installs the missing apps via powershell (obviously after the whole OOBE ordeal) I can share a zip with all of them (Notepad, Terminal, Store and Security Center)

**Comment by JonatanCz** [comment]
I would love to get that script. Can you send it here?

**Comment by SunnyM00n** [comment]
MM, it's not letting me attach it to the issue post, i made a repo instead [https://github.com/SunnyM00n/Windows11AppsScript](url)

**Comment by abbodi1406** [comment]
I guess it's time to close, since the converter / uup dump now support adding the Apps
