### ISSUE TITLE
Local Language Experience Packs (LXPs) are incorrect after downloading

### ISSUE THREAD

**Issue by ilikeyi** [uup-dump/website#143]
Local Language Experience Packs (LXPs) are incorrect after downloading.

https://uupdump.net/findfiles.php?id=a501dcf0-9166-4273-aba5-637c07189e06

E.g:
File name: LanguageExperiencePack.en-us.Neutral.appx
Download link: https://uupdump.net/getfile.php?id=a501dcf0-9166-4273-aba5-637c07189e06&file=LanguageExperiencePack.zh-cn.Neutral.appx

After the download is complete, the version is: 21388.1.1.0

the correct one is:

https://store.rg-adguard.net/
Enter: https://www.microsoft.com/store/productId/9NRMNT6GMZ70

After searching for: 22000, select the corresponding file:
Microsoft.LanguageExperiencePackzh-CN_22000.17.50.0_neutral__8wekyb3d8bbwe.appx

The installed version after downloading is: 22000.17.15.50.0

Looking forward to fixing this bug.

![error](https://user-images.githubusercontent.com/73377514/157669308-90ff714d-f49d-44b4-bd35-cb35c2f5ee00.png)

**Comment by abbodi1406** [comment]
- The files are detemined by the release metadata, which is built and originated from the source (Microsoft), UUP dump just deliver it
- LXPs are not supported or preferred for fully-localized languages in Windows 11, maybe that's why they don't included latest version
- https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-language-imaging-in-windows-11/ba-p/2758043

**Comment by ilikeyi** [comment]
> * 文件由发布元数据确定，该元数据构建并源自源（Microsoft），UUP 转储只是交付它
> * Windows 11 中完全本地化的语言不支持或首选 LXP，也许这就是它们不包含最新版本的原因
> * https://techcommunity.microsoft.com/t5/windows-it-pro-blog/update-to-language-imaging-in-windows-11/ba-p/2758043

I wrote a script today, because I made a Windows 11 multilingual offline add, before reinstalling InBox Apps, I had to add the local language experience (LXPS), I downloaded it manually.

It took me 4 hours to download 109 local language experience packs again today.

Then I wrote the script, according to your website, the result download does not match.

Dear, is there any way to download the ones starting with 22000.*?

Can you help me with getting the interface. I have uploaded LXPs.zip , run Download.ps1

[LXPs.zip](https://github.com/uup-dump/website/files/8226444/LXPs.zip)

![911](https://user-images.githubusercontent.com/73377514/157739847-a72fa18c-d152-413e-be27-6d231b8c5117.png)

**Comment by abbodi1406** [comment]
This is the latest build with 22000.* LXPs = 22000.9.17.0
https://uupdump.net/findfiles.php?id=f2031a5d-6837-4844-91a7-7b7b20e48362&q=LanguageExperiencePack

**Comment by ilikeyi** [comment]
> This is the latest build with 22000.* LXPs = 22000.9.17.0 https://uupdump.net/findfiles.php?id=f2031a5d-6837-4844-91a7-7b7b20e48362&q=LanguageExperiencePack

Thank you for your reply, but there is still a small problem, it is not the latest after downloading.

The download interface you provided is 22000.*, which is not the latest version.

On the left is the automatic download of the script, and on the right is manually going to https://store.rg-adguard.net, one by one.



![Untitled](https://user-images.githubusercontent.com/73377514/157863572-e75f5033-f8f7-4dae-a9f9-07feabafc9d6.png)

![2](https://user-images.githubusercontent.com/73377514/157863587-103f8611-4ba0-4e2d-b4aa-6d32083caff7.png)

**Comment by abbodi1406** [comment]
> Thank you for your reply, but there is still a small problem, it is not the latest after downloading.

I know, but it's the last possible version available from UUP builds
UUP dump does not control the delivered files version

you can use this powershell script to automate download from store.rg-adguard.net
https://github.com/MattiasC85/Scripts/blob/master/OSD/Download-AppxFromStore.ps1
