### ISSUE TITLE
Windows 11 issue 

### ISSUE THREAD

**Issue by andythegreat87** [uup-dump/website#145]
One Windows 11, I cannot get the UUP to work, when I press any key it does not work , I also get this

_"Current directory contains spaces in its path.
Please move or rename the directory to one not containing spaces.

Press any key to continue . . ."_

after that, it closes, nothing happens

**Comment by raspiduino** [comment]
Like the output suggested, you should move the scripts and its files to a folder that not contains space in its path.
For example you can create a folder in `C:` like `C:\uupdump_script` and move the scripts there.

Thanks!
