### ISSUE TITLE
Option required to split install.wim

### ISSUE THREAD

**Issue by psndna88** [uup-dump/website#151]
Please add option to split install.wim to .swm files
I have to do this because "yumi UEFI multiboot" does not support exfat/ntfs 

I had to do it this way to overcome fat32 limitations:
Dism /Split-Image /ImageFile:D:\Windows_11\22000_stable_build\extract\sources\install.wim /SWMFile:D:\Windows_11\22000_stable_build\extract\sources\install.swm /FileSize:3900
Two install.swm files are generated, then delete install.wim

**Comment by awuctl** [comment]
Not sure what that tool does but I assure you the Windows installer doesn't need help with NTFS.
As long as you can boot the installer, it will find `sources/`.

Newer firmware can boot from NTFS volumes by itself - you need only extract the ISO onto the partition from which you will boot.
For older firmware that can boot from FAT32/-16/-12 you can extract the installer (`boot/`, `efi/`, `bootmgr`, `bootmgr.efi`, `setup.exe` and `sources/boot.wim`)  onto a FAT partition and make another (**NTFS**) one onto which you can extract only the `sources` folder (skipping `sources/boot.wim`. This will boot and install normally.

For anything more complicated (multiple images) you should consider making your own WinPE scripts or merging WIMs.
Personally I see no reason to complicate the converter even further.
