### ISSUE TITLE
[Issue]Fail to load https://proxied.uupdump.net/

### ISSUE THREAD

**Issue by ktns01** [uup-dump/website#153]
https://proxied.uupdump.net/ is now offline and report Error 526 "Invalid SSL certificate".
Is there anyone who can explain why to me? I'm in China and couldn't access [https://uupdump.net/?lang=zh-cn](https://uupdump.net/?lang=zh-cn) normally.

**Comment by spali** [comment]
I just discovered that CNAME of `api.uupdump.net` does not resolve to an IP. 
Could it be related?

**Comment by domikuss** [comment]
I support, the same problem:(
