### ISSUE TITLE
How to remove extra CAB file to make ISO smaller?

### ISSUE THREAD

**Issue by anyuzu99** [uup-dump/website#154]
by default, uup-dump download a lot of unnecessary large file, then pack them into the image:
- `Microsoft-Windows-Hello-Face-Package-amd64_4eef75eb.cab` 65.1 MB
- `Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-amd64.cab` 64.4 MB
- `Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-amd64.cab` 50.2 MB
- and many other Wi-Fi drivers

If there is a way to prevent these `.cab` from packing into the image?

**Comment by abbodi1406** [comment]
No
all downloaded cab / esd files are required to build install.wim
