### ISSUE TITLE
Can uup dump download and make multi language windows installer iso?

### ISSUE THREAD

**Issue by chinanoahli** [uup-dump/website#162]
I already tried to download different languages of same version of the windows installer, and put them together.
But the converter seems can not create multi language windows installer iso at all.

I did some search, but I got nothing, please tell me how if it is possible, thanks.

**Comment by abbodi1406** [comment]
No possible
create regular one language ISO, then add other languages + updates
https://github.com/abbodi1406/WHD/raw/master/scripts/W10MUI_20.7z

**Comment by chinanoahli** [comment]
Thanks, I will try this later.
