### ISSUE TITLE
unable to access uupdump website down

### ISSUE THREAD

**Issue by mrusli70** [uup-dump/website#167]
Hi

Today, i unable to access uupdump website due to 502 Bad Gateway. The web site is currently down.  Could please check your website.

**Comment by stevenzhu25** [comment]
I downloaded a copy of [website](https://github.com/uup-dump/website), [api](https://github.com/uup-dump/api) ,[fileinfo](https://github.com/uup-dump/fileinfo) and [packs](https://github.com/uup-dump/packs) on my own server and spawn up https://uupdump.stevenz.download/
Not a long term solution, but hopefully would last long enough for them to get uupdump.net back up.
