### ISSUE TITLE
22622.575 is 22621.575

### ISSUE THREAD

**Issue by zakiloki0** [uup-dump/website#168]
I want download 22622.575 version but seems the script of 22622.575 download the 22621.575

This is a UUP error or maybe Microsoft deletes 22622.575?

**Comment by abbodi1406** [comment]
22622 is fake build number, you can get it only by installing/integrating Enablement Package KB5015669

**Comment by zakiloki0** [comment]
> 22622 is fake build number, you can get it only by installing/integrating Enablement Package KB5015669

But if I'm not wrong, if I go to the betas section, both appears and when generating the script, the name is 22622.575_amd64_en...

**Comment by abbodi1406** [comment]
Yes, that's the intended target build, but it can only be accomplished by Updates integration
just like Windows 10 19045/19044/19043/19042

**Comment by zakiloki0** [comment]
> Yes, that's the intended target build, but it can only be accomplished by Updates integration just like Windows 10 19045/19044/19043/19042

Ahhh I understand :) Thank you @abbodi1406 your work is awesome!
