### ISSUE TITLE
Site SSL certificate is not trusted

### ISSUE THREAD

**Issue by FadeMind** [uup-dump/website#171]
Hi 

SSL Cert is not trusted anymore. 
Forcing connecting is possible, but not anymore via HTTPS. 

![20220824-1661367531](https://user-images.githubusercontent.com/9846948/186501118-49549b20-2b14-4a81-add8-7eb86911f3c3.png)
![20220824-1661367553](https://user-images.githubusercontent.com/9846948/186501124-cda32445-37da-4d76-9227-7f6413005eec.png)

**Comment by jh30uk** [comment]
Same and files fail to download due to not being a secure server, a lot lately I cannot get the UK/GB version of Win 11 Dev without restarting 10x to get past errors.

I have tried the separate aria.exe trick.

**Comment by lazerl0rd** [comment]
> Same and files fail to download due to not being a secure server, a lot lately I cannot get the UK/GB version of Win 11 Dev without restarting 10x to get past errors.
> 
> I have tried the separate aria.exe trick.

If you'd like to get past the initial failures at least, you can add the `--check-certificate=false` argument to any downloads from `https://uupdump.net` initiated in the script as follows:

![image](https://user-images.githubusercontent.com/24303423/186508223-fab1f8d3-7a76-4694-88aa-ba0d640322d7.png)

Not sure if that was exactly what you were looking for, but hopefully that helps someone.

**Comment by jh30uk** [comment]
Thanks, all working normally now (just took some, time out)
