### ISSUE TITLE
[feature suggestion] sortable table at https://uupdump.net/known.php

### ISSUE THREAD

**Issue by eladkarako** [uup-dump/website#172]
hello,  
making the table at https://uupdump.net/known.php  
sortable would really help finding stuff,  
it is client side so it won't cause server-side overhead in any way which is nice.

if it helps,  
I've used this "drop-in code",  
to sort the whole table by date,  
putting the most recent additions on top

```js
function natural_compare(a,b){
  let ax=[]
     ,bx=[]
     ;
  if("function" === typeof natural_compare.extraction_rule){
   a = natural_compare.extraction_rule(a);
   b = natural_compare.extraction_rule(b);
  }
  //numbers can be normalized (original value is fine, - it is just another kind of extraction-rule.
  a = ("number" === typeof a) ? String(a) : a;  
  b = ("number" === typeof b) ? String(b) : b;

  //but not much else..
  if("string" !== typeof a){return 0;}
  if("string" !== typeof b){return 0;}

  a.replace(/(\d+)|(\D+)/g,function(_,$1,$2){ ax.push([$1 || Infinity, $2 || ""]); });
  b.replace(/(\d+)|(\D+)/g,function(_,$1,$2){ bx.push([$1 || Infinity, $2 || ""]); });
  while(ax.length>0 && bx.length>0){
   let an = ax.shift()
      ,bn = bx.shift()
      ,nn = (an[0] - bn[0]) || an[1].localeCompare(bn[1])
      ;
   if(0 !== nn){ return nn; }
  }
  return (ax.length - bx.length);
};


let tbody = document.querySelector("table tbody")
   ,rows  = Array.from(tbody.querySelectorAll("tr"))
  ;

natural_compare.extraction_rule = function(a){
  return a.firstElementChild.nextElementSibling.nextElementSibling.innerText;
}

rows = rows.sort(natural_compare).reverse();

rows.forEach((row) => { tbody.appendChild(row); })

```

it is very lean and fast,  
but not very user friendly ;) 

<hr/>

probably the easiest way is to use https://www.kryogenix.org/code/browser/sorttable/  
by including `<script crossorigin="anonymous" src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>` at the page's head and adding `class="sortable"` to the table.

I would also advise to make use of the natural sort algorithm above by adding  

```html
<script>sorttable.sort_alpha = natural_compare;</script>
```

somewhere.

**Comment by eraseyourknees** [comment]
This feature has been added by 11d2a8f4d8fc5292b834362fc087bb0fb3001ddd. JavaScript approach will be considered in future.
