### ISSUE TITLE
Issue with missing language builds

### ISSUE THREAD

**Issue by SeSeKenny** [uup-dump/website#18]
There is a either missing metadata on the downloads source or certain builds are 'language less' and it prevents the workflow from succeeding. Examples are below, 

The website appears to have a specific message for this scenario, however the inability to create builds due to this. Removing the 'pack' directive dumps out file listings, but I imagine sending that entire set to aria is overkill (all languages essentially).

https://uupdump.ml/selectedition.php?id=02cfe468-8c7d-4e2c-89b6-93524e69993b&pack=en-us

https://uupdump.ml/get.php?id=02cfe468-8c7d-4e2c-89b6-93524e69993b&pack=en-us&edition=0&aria2=2
doesnt work, however
https://uupdump.ml/get.php?id=02cfe468-8c7d-4e2c-89b6-93524e69993b&edition=0&aria2=2
does work, but no filter on language

I will begin parsing through some code as well.

**Comment by whatever127** [comment]
Updates such the one you have used as example do not have metadata required to build a working ISO. Because of this there is no way to build a list of packages for automatic download. These updates are provided are provided only to access features on demand packages and language packs.

**Comment by SeSeKenny** [comment]
Darn, would be nice for server builds to work period but oh well thats on MSFT. It is crazy how close they are though, a simple diff of working build vs not, there aren't a tonne of packages appearing to be missing, although arguably the most important ones 'core-edition' type stuff, are missing.
