### ISSUE TITLE
[feature suggestion] matching phrases in any order, in known.php

### ISSUE THREAD

**Issue by eladkarako** [uup-dump/website#185]
currently users searching `preview windows amd64`  
and users searching for `windows preview amd64`  
will get two very different results.  

<hr/>

https://uupdump.net/known.php?q=preview+windows+amd64&sort=1  

```
Cumulative Update Preview for Windows 10 Version 20H2 (19042.1949) amd64	x64	2022-08-26 22:26:05 UTC
Cumulative Update Preview for Windows 10 Version 21H1 (19043.1949) amd64	x64	2022-08-26 22:25:52 UTC
Cumulative Update Preview for Windows 10 Version 21H2 (19044.1949) amd64	x64	2022-08-26 22:25:38 UTC
...
```

https://uupdump.net/known.php?q=windows+preview+amd64&sort=1  

```txt
Windows 11 Insider Preview 10.0.22621.590 (ni_release) amd64	x64	2022-09-01 18:06:38 UTC
Cumulative Update for Windows 11 Insider Preview (10.0.22621.590) amd64	x64	2022-09-01 17:00:53 UTC
Windows 11 Insider Preview 10.0.22622.590 (ni_release) amd64	x64	2022-09-01 17:00:44 UTC
Windows 11 Insider Preview 25193.1000 (rs_prerelease) amd64	x64	2022-09-01 17:00:24 UTC
```

<hr/>

the results are limited by the order of the phrases in the query.
it is like matching those, very different regular expressions:  
`/preview.*windows.*amd64/i` and `/windows.*preview.*amd64/i`  

it might be useful to allow loose matching.

ignoring complex stuff such as `similar_text` or fuzzy matching,  
this  
https://www.google.com/search?q=regular+expression+matching+words+in+any+order  

got me (php) https://stackoverflow.com/questions/18746290/regex-to-match-words-in-any-order 
and (javascript) https://stackoverflow.com/questions/55116510/regex-specified-words-in-any-order

which I now use everywhere.  

thought it might be useful.

**Comment by abbodi1406** [comment]
Why complicate things and possibly break search? most users would look for specific build number

**Comment by eladkarako** [comment]
> most users

what are you base that assumption on?  

I, in-fact am a user,  
and I was looking for preview build. 

`preview 11` got me nowhere,  
but `11 preview` got me what I want,  
I can assure you at least some of the visitor will assume no results  
would actually mean no results,  
linguistically it should have no difference,  
and for that matter, it will only add more results to the list,  
so it won't hurt anything, and will make the query more intuitive.   
 
you've already improved the website a lot by adding a sort by date,  
and fixed the query to be sent using `+` instead of `%20`,  
it is really cool that you all built this website from scratch,  
it is really lite and straight-forward.   

thanks.

**Comment by eraseyourknees** [comment]
Implementing this would make the search absolutely useless. As in your example `11 preview` would result in Windows 11 and hundreds other builds that happened to have `11` in the name. These results would definitely not help someone who is unable to figure out a correct search phase and would only cause issues to everyone else.

**Comment by eladkarako** [comment]
> hundreds other builds that happened to have `11` in the name.

that example doesn't makes a lot of sense.

that's fine though,  
it is just a [feature suggestion] after-all.
