### ISSUE TITLE
Can't Download due to "network problem"

### ISSUE THREAD

**Issue by ktns01** [uup-dump/website#188]
Downloads from uupdump.net keep failing due to "network problem" and I can't explain why.
I'm sure my network is totally fine.
Here's the gif. Hope this would help.
![动画](https://user-images.githubusercontent.com/93424632/189505722-e819d42a-5df7-4d92-a0a8-85a0520558b1.gif)

**Comment by awuctl** [comment]
cool pixiv downloads you got there

**Comment by awuctl** [comment]
sure won't report this to abuse@chinamobile.com

**Comment by eraseyourknees** [comment]
fixed.

**Comment by wchisme2000** [comment]
前阵子开始server镜像就不能下载了，总是到最后一个文件就失败了，其他消费版的WIN10和11还没啥问题，就是server的镜像有问题。
