### ISSUE TITLE
MS blocking the download of server images?

### ISSUE THREAD

**Issue by wchisme2000** [uup-dump/website#190]
Fail on the last file every time
09/15 11:28:27 [ERROR] CUID#20 - Download aborted. URI=https://uupdump.sf.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/6c9bd997-bbdd-4c74-9ca4-6ce718daeb50?P1=1663248494&P2=404&P3=2&P4=ie918%2f5IwfCcFuqlu4LOfnVq6s7PaZIP1FgF%2fYKxFcLkPkZ870HARawz8O0UHx4v7Av7UlXEnr%2bvV3gH2kZo5g%3d%3d
Exception: [SocketCore.cc:885] errorCode=1 Failed to receive data, cause: Error: 指定的句柄无效
(80090301)

09/15 11:28:27 [NOTICE] Download GID#85d0df5c0c02906c not complete: UUPs/ServerStandard_zh-cn.esd

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
eab39a|OK  |       0B/s|UUPs/Windows10.0-KB5007374-x64.cab
43b1df|OK  |       0B/s|UUPs/Windows10.0-KB5016774-x64.cab
7bf76d|OK  |       0B/s|UUPs/SSU-20348.945-x64.cab
d7b058|OK  |       0B/s|UUPs/Windows10.0-KB5015022-x64.cab
a83882|OK  |       0B/s|UUPs/Windows10.0-KB5017316-x64.cab
85d0df|ERR |   166KiB/s|UUPs/ServerStandard_zh-cn.esd

**Comment by earthmoon** [comment]
同样的问题，请问怎么解决呢？
