### ISSUE TITLE
media driver

### ISSUE THREAD

**Issue by Arjun-Deshpande** [uup-dump/website#200]
When I install win10 or 11 on my Mac m1 max 32GB I get this media driver missing error pls help me
<img width="1512" alt="Screenshot 2022-09-23 at 14 55 28" src="https://user-images.githubusercontent.com/73472482/191976921-590e0f38-1d65-44fa-84fa-6a42d4797c11.png">

**Comment by eraseyourknees** [comment]
We at UUP dump do not condone the usage of ARM64 Windows in any way, shape, form or context.
Expect **no support for ARM64 indefinitely** unless you're willing to gift us an M2 Mac.

**Comment by Arjun-Deshpande** [comment]
im willing to gift the Mac I need this vm

**Comment by Arjun-Deshpande** [comment]
@eraseyourknees
