### ISSUE TITLE
Error when downloading the files with aria2

### ISSUE THREAD

**Issue by Komas19-Pages-Dev-382939485bADMIN** [uup-dump/website#202]
Hello, i tried download Windows 11 Insider Preview 25206.1000 (rs_prerelease) amd64 using aria2
![image](https://user-images.githubusercontent.com/82937056/192099630-2111c8e4-8373-4d01-b7b7-801321e1ed7a.png)

but i got across an error.

Log file:
[aria2_download.log](https://github.com/uup-dump/website/files/9638756/aria2_download.log)

**Comment by abbodi1406** [comment]
You could not zip 15 MB log file?

download errors are expected sometimes, just run the download script again (and again until all files are downloaded)

**Comment by Komas19-Pages-Dev-382939485bADMIN** [comment]
i have restarted 3 times, im gonna try again.

**Comment by eraseyourknees** [comment]
Restart until it works or get a better internet connection.
