### ISSUE TITLE
Download build 25211  and previous one not working

### ISSUE THREAD

**Issue by JanB1948** [uup-dump/website#211]
The generated scripts were aborted due to multiple download errors ( checksum errors).

**Comment by eraseyourknees** [comment]
I do not own any of Microsoft's update delivery servers.

**Comment by JanB1948** [comment]
I believe I might have to be  more specific:
The script of the latest Dev  Channel build I created using UUPDUM.net:”25211.1001_amd64_nl-nl_professional_ae89f6ab_convert” is  generating lots of download errors when I  run it as admin .
Is that using the common MS Update servers?
The previous  version did the same
The regular Microsoft update ( MS  Insider)  ran OK.
Regards

**Comment by JanB1948** [comment]
![UUPDump Errors](https://user-images.githubusercontent.com/114811587/193454218-6a88c895-7c47-4f15-9d4b-dd2077e24655.jpg)

**Comment by RealEnthousiast** [comment]
I have experienced the same thing last week, i needed to run the download cmd 4 times to get it to pass the download stage and start the conversion.

**Comment by JanB1948** [comment]
I believe I might have to be  more specific:

The script of the latest Dev  Channel build I created using UUPDUM.net:”25211.1001_amd64_nl-nl_professional_ae89f6ab_convert” is  generating lots of download errors when I  run it as admin .

Is that using the common MS Update servers?

The previous  version did the same

The regular Microsoft update ( MS  Insider)  ran OK.

Regards

 

Van: eraseyourknees ***@***.***> 
Verzonden: zondag 2 oktober 2022 02:18
Aan: uup-dump/website ***@***.***>
CC: JanB1948 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [uup-dump/website] Download build 25211 and previous one not working (Issue #211)

The download script generated  using UUPDUP.net

I do not own any of Microsoft's update delivery servers.

**Comment by JanB1948** [comment]
Generating  script and downloing  and gererating the iso  for build 25217 went OK,
