### ISSUE TITLE
Website does not display properly

### ISSUE THREAD

**Issue by mistertheloaf** [uup-dump/website#213]
As of Sept. 30, 2022 the website https://uupdump.net/  does not display properly.  Tried 3 different browsers with identical results on all:

Firefox (Windows PC)
Palemoon (Windows PC)
Chrome (Windows PC)

![Dump-1](https://user-images.githubusercontent.com/70538412/193419236-15488e71-5ca0-4779-b1d3-de72de327387.jpg)

![Dump-2](https://user-images.githubusercontent.com/70538412/193419245-615a68b1-bcca-4aab-9145-a9928dcd251c.jpg)

**Comment by eraseyourknees** [comment]
Works on my machine.
![works](https://user-images.githubusercontent.com/112027564/193432619-fe80635a-1c42-4baf-913e-274aebc598d6.png)
