### ISSUE TITLE
I changed the ConvertConfig.ini , but it doesn't work

### ISSUE THREAD

**Issue by clukgao** [uup-dump/website#215]
SkipApps     =0
AppsLevel    =2
CustomList   =1
and then Choose the wanted apps in CustomAppsList.txt, but it doesn't work. I can't see the apps in my windows

**Comment by abbodi1406** [comment]
Did you watch the conversion / updating progress?
post your modified CustomAppsList.txt

**Comment by clukgao** [comment]
### Common Apps / Client editions all
# Microsoft.WindowsStore_8wekyb3d8bbwe
# Microsoft.StorePurchaseApp_8wekyb3d8bbwe
# Microsoft.SecHealthUI_8wekyb3d8bbwe
Microsoft.VCLibs.140.00_8wekyb3d8bbwe
# Microsoft.Windows.Photos_8wekyb3d8bbwe
# Microsoft.WindowsCamera_8wekyb3d8bbwe
Microsoft.WindowsNotepad_8wekyb3d8bbwe
Microsoft.Paint_8wekyb3d8bbwe
# Microsoft.WindowsTerminal_8wekyb3d8bbwe
# Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
# MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
# Microsoft.WindowsAlarms_8wekyb3d8bbwe
Microsoft.WindowsCalculator_8wekyb3d8bbwe
# Microsoft.WindowsMaps_8wekyb3d8bbwe
# Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe
Microsoft.ScreenSketch_8wekyb3d8bbwe
# microsoft.windowscommunicationsapps_8wekyb3d8bbwe

but when i set SkipApps=0 AppsLevel=0 CustomList=1, then it works

**Comment by clukgao** [comment]
\# Microsoft.WindowsStore_8wekyb3d8bbwe
\# Microsoft.StorePurchaseApp_8wekyb3d8bbwe
\# Microsoft.SecHealthUI_8wekyb3d8bbwe
Microsoft.VCLibs.140.00_8wekyb3d8bbwe
\# Microsoft.Windows.Photos_8wekyb3d8bbwe
\# Microsoft.WindowsCamera_8wekyb3d8bbwe
Microsoft.WindowsNotepad_8wekyb3d8bbwe
Microsoft.Paint_8wekyb3d8bbwe
\# Microsoft.WindowsTerminal_8wekyb3d8bbwe
\# Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
\# MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy
\# Microsoft.WindowsAlarms_8wekyb3d8bbwe
Microsoft.WindowsCalculator_8wekyb3d8bbwe
\# Microsoft.WindowsMaps_8wekyb3d8bbwe
\# Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe
Microsoft.ScreenSketch_8wekyb3d8bbwe

but when i set SkipApps=0, AppsLevel=0, CustomList=1, then it works

**Comment by abbodi1406** [comment]
I could not duplicate that, but i'll double-check, thanks for notifying
