### ISSUE TITLE
Error when downloading ARM Windows 10 UUP

### ISSUE THREAD

**Issue by gradygambrell** [uup-dump/website#216]
I was trying to download the ARM version of Windows 10 via UUP and it gave me this exception:
Exception caught
Exception: [download_helper.cc:563] errorCode=1 Failed to open the file files/converter_multi, cause: File not found or it is a directory

We have encountered an error while downloading files.

I am using macOS Ventura (22A5373b) and is using the beta version of CLTs

**Comment by eraseyourknees** [comment]
Can't reproduce on GNU/Linux. No one here owns a Mac, you are on your own.
