### ISSUE TITLE
The generated ɪꜱᴏs downloads/includes the Windows ᴘᴇ version of ᴅɪꜱᴍ instead of the plain version.

### ISSUE THREAD

**Issue by ytrezq** [uup-dump/website#218]
Since I upgraded to a specific Windows version generated with ᴜᴜᴘ, I can no longer use any ᴅɪꜱᴍ `/online` commands.

    C:\> dism /Online /Cleanup-Image /Restorehealth
    Version : 10.0.21301.1000

    Error: 50

    DISM does not support servicing Windows PE with the /Online option

    C:\>
Of course, I’m not running in Windows ᴘᴇ mode.

**Comment by eraseyourknees** [comment]
>10.0.21301.1000

Why should I care about your random ass Insider build from February 2021?

**Comment by ytrezq** [comment]
@eraseyourknees because it affect more récent Windows 11 builds? **Please reopen**

**Comment by eraseyourknees** [comment]
Don't care, works on my (virtual) machine.
![image](https://user-images.githubusercontent.com/112027564/196766778-8c3d2871-9e42-4b20-b91f-0ce861039545.png)
