### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by michelle1574** [uup-dump/website#222]
When downloading from findfiles.php with tag aria2=2 each link in a script would redirect to getfile.php without the tag aria2=2 which causes an error

**Comment by abbodi1406** [comment]
Adding the tag would generate another aria2 download script, which also will cause an error

findfiles is mainly for manual download of few specific files, not bulk download

**Comment by michelle1574** [comment]
Is there an solution to download with slow internet? If someone has slow internet - microsoft removes download possibility after time - 403 error
