### ISSUE TITLE
Unable to retrieve data from Windows Update servers. Reason: XML_PARSE_ERROR while dowmloading ARM64 builds

### ISSUE THREAD

**Issue by arunniperk** [uup-dump/website#223]
Downloading aria2c.exe...
Downloading 7zr.exe...
Downloading uup-converter-wimlib.7z...                                                                                  
Verifying aria2c.exe...
Verifying 7zr.exe...
Verifying uup-converter-wimlib.7z...

It appears all the dependencies are ready.

Extracting UUP converter...

Retrieving aria2 script...

05/15 23:19:21 [NOTICE] Downloading 1 item(s)

05/15 23:19:22 [NOTICE] CUID#7 - Redirecting to https://uupdump.net/get.php?id=03969680-21c4-463a-bc16-e26137be40e2&pack=en-us&edition=core;professional&aria2=2
[#f9a25e 0B/0B CN:1 DL:0B]
05/15 23:19:25 [NOTICE] Download complete: C:/22000/files/aria2_script.19109.txt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
f9a25e|OK  |   1.9KiB/s|C:/22000/files/aria2_script.19109.txt

Status Legend:
(OK):download completed.

Unable to retrieve data from Windows Update servers. Reason: XML_PARSE_ERROR
If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.

Press any key to continue . . .

**Comment by dziugas1959** [comment]
Can confirm.

**Comment by sabaasa** [comment]
running into same issue with 19045.3300 AMD64

**Comment by abbodi1406** [comment]
Works fine here currently
temporary glitches are expected in any online service

**Comment by DominikHoffmann** [comment]
I have tried about five different packages, and I have that error in every case.
