### ISSUE TITLE
Windows 10 20H2 and 21H1 for ARM64 are actually 20H1

### ISSUE THREAD

**Issue by davidebeatrici** [uup-dump/website#65]
https://www.uupdump.net/selectlang.php?id=60df8fbc-dfef-462d-8cb4-aee6a2cee0c1

![](https://user-images.githubusercontent.com/5897523/109899324-f9ed9380-7c95-11eb-9614-0b0e8a236b8b.png)
![](https://user-images.githubusercontent.com/5897523/109899251-de828880-7c95-11eb-98c5-d533a56ff7bf.png)

The name of the downloaded archive is `19042.804_arm64_en-us_professional_60df8fbc_convert_virtual.zip`, but the name of the built ISO is `19041.1_MULTI_ARM64_EN-US.ISO`.

**Comment by davidebeatrici** [comment]
It's also worth noting that there are several issues, which I'm not sure are related to 20H1 or this specific release:

- Device manager cannot be opened directly.
- Windows Update fails to update to 20H2: `0x800f080a`
- When launching some applications, such as `cmd`, a COM Surrogate (`dllhost.exe`) process is spawned and it has to be killed in order for the application to start.
- OneDrive installation (it triggers automatically at boot) never completes and the installer keeps using one thread at 100%.

I reinstalled many times and also switched from Enterprise to Pro, but the issues persist.

**Comment by davidebeatrici** [comment]
Same with https://www.uupdump.net/selectlang.php?id=525348a4-7ea4-47bd-8857-558546584fb6, only the archive name changes.

**Comment by davidebeatrici** [comment]
Same with https://www.uupdump.net/selectlang.php?id=d10b1292-902e-4b1c-9cfb-6805d1ef70fb (20H2).

**Comment by davidebeatrici** [comment]
https://www.uupdump.net/selectlang.php?id=3d6e44b9-d896-4580-b17a-3162517fbcdb cannot be downloaded at all.

From https://www.uupdump.net/get.php?id=3d6e44b9-d896-4580-b17a-3162517fbcdb&pack=en-us&edition=professional&aria2=2:
> #UUPDUMP_ERROR:EMPTY_FILELIST

**Comment by luzeagithub** [comment]
> The name of the downloaded archive is `19042.804_arm64_en-us_professional_60df8fbc_convert_virtual.zip`, but the name of the built ISO is `19041.1_MULTI_ARM64_EN-US.ISO`.

You've used the Linux converter, from the README of the converter:
> For obvious reasons this script will never support integration of Cumulative Updates to created images.
Because 20H2 and 21H1 are technically updates and not upgrades, they can't be integrated into the ISO on Linux.

> 
> 
> It's also worth noting that there are several issues, which I'm not sure are related to 20H1 or this specific release:
> 
>     * Device manager cannot be opened directly.
> 
>     * Windows Update fails to update to 20H2: `0x800f080a`
> 
>     * When launching some applications, such as `cmd`, a COM Surrogate (`dllhost.exe`) process is spawned and it has to be killed in order for the application to start.
> 
>     * OneDrive installation (it triggers automatically at boot) never completes and the installer keeps using one thread at 100%.
> 
> 
> I reinstalled many times and also switched from Enterprise to Pro, but the issues persist.

Assuming you've used the 19041.1 (20H1) image from above without any updates integrated, that can be a normal behavior and was patched in a newer update.

> 
> 
> https://www.uupdump.net/selectlang.php?id=3d6e44b9-d896-4580-b17a-3162517fbcdb cannot be downloaded at all.
> 
> From https://www.uupdump.net/get.php?id=3d6e44b9-d896-4580-b17a-3162517fbcdb&pack=en-us&edition=professional&aria2=2:
> 
> > #UUPDUMP_ERROR:EMPTY_FILELIST
> 
> I assume the files are not available yet? It's also the case for https://www.uupdump.net/selectlang.php?id=d6a39dd1-a5f5-4ecd-aa41-0311468baaeb.

The `The server has returned an empty file list.` message appears when **Microsoft** returned an empty file list, not the UUP dump server.

**Comment by davidebeatrici** [comment]
Oh, I completely missed that. Sorry!

Isn't 21H1 supposed to be a complete release though? I thought Windows 10 versions followed a "tick-tock" pattern.

> The `The server has returned an empty file list.` message appears when **Microsoft** returned an empty file list, not the UUP dump server.

Okay, that's what I thought.

**Comment by luzeagithub** [comment]
> Isn't 21H1 supposed to be a complete release though? I thought Windows 10 versions followed a "tick-tock" pattern.
21H1 = 2004 as base with 20H2 EP* + 21H1 EP*

* Enablement Package, an update that enables the features integrated in the system by previous updates. For example, if you have a fully updated 2004 installation, the 20H2 features and 21H1 features are already integrated, but not enabled.

> Okay, that's what I thought.
I removed the builds manually now, they'll appear again as soon as their file list can be retrieved.

**Comment by davidebeatrici** [comment]
I confirm the Windows converter correctly generates a 21H1 ISO (`19043.844.210209-1708.21H1_RELEASE_SVC_PROD3_CLIENTMULTI_A64FRE_EN-US.ISO`).

Perhaps a warning should be added on the page of the affected builds and/or when running the Linux converter?

> 21H1 = 2004 as base with 20H2 EP* + 21H1 EP*
> 
> *Enablement Package, an update that enables the features integrated in the system by previous updates. For example, if you have a fully updated 2004 installation, the 20H2 features and 21H1 features are already integrated, but not enabled.

I see, thanks for the explanation!

> I removed the builds manually now, they'll appear again as soon as their file list can be retrieved.

Sounds good.

**Comment by luzeagithub** [comment]
I added a warning to the multiplatform UUP converter when updates are detected:
```
$ ./convert.sh
UUP Converter v0.6.3
Note: This script does now allow the integration of updates.
Use the Windows version of the converter to integrate updates.
CAB -> ESD: microsoft-windows-mediaplayer-package-amd64
CAB -> ESD: microsoft-windows-quickassist-package-amd64
CAB -> ESD: microsoft-windows-hello-face-migration-package-amd64
...
```

**Comment by davidebeatrici** [comment]
Excellent, thanks!

**Comment by davidebeatrici** [comment]
Just for reference: turns out all x86 apps appear to be stuck in an infinite loop, even PowerShell.

The latest Insider Preview (which also provides x64 emulation) seems to work fine.
