### ISSUE TITLE
In FAQ, the 3rd question now become invalid, recommend delete.

### ISSUE THREAD

**Issue by JRJSheep** [uup-dump/website#84]
In FAQ，the 3rd question now become invalid, recommend delete this question.

**Comment by luzeagithub** [comment]
it is not completely invalid, it still applies to older builds of Windows Server

**Comment by JRJSheep** [comment]
Since it corresponds to the old version, this question and answer should be modified to some extent. Make it adapt to the alternation of old and new versions.

**Comment by JRJSheep** [comment]
I was changed the FAQ 3rd question localization text, this issue will be closed.
